### ISSUE TITLE
Setter for Value Types in element.go?

### ISSUE THREAD

**Issue by IChocked** [suyashkumar/dicom#107]
### Version
Pre-release v1.0.0-alpha.2

### Background
One of the variables for the `Element` struct is `Value`, which is itself a `Value` struct (see [here](https://github.com/suyashkumar/dicom/blob/v1.0.0-alpha.2/element.go#L19)). This struct presumably stores the main data for the element (e.g. patient name). Each Value struct (e.g. `StringsValue`) contains a single variable called `value`. `value`, however, is an unexported value because it's lowercase and the implementer of the library has no access to it.

### Problem
Unable to create a new element with an actual value because we don't have access to the `value` variable in any *Value struct outside the dicom package. For example, attempting to create an element with this:
```
studyDescElem := dicom.Element{
		Tag: dicomtag.Tag{0x0008, 0x1030},
		RawValueRepresentation:  "LO",
		Value: &dicom.StringsValue{
			value: []string{studyDescription},
		},
	}
```
Yields the error `unknown field 'value' in struct literal of type dicom.StringsValue`

### Expected behavior
It is useful for the implementer to be able to create an Element struct (e.g. for dicom generation during unit testing), like this:

```
e := &Element{
		Tag:                    tag.Rows,
		ValueRepresentation:    tag.VRInt32List,
		RawValueRepresentation: "US",
		Value: &intsValue{
			value: []int{100},
		},
	}
```

### Recommendation
Add setter functions for each *Value struct (e.g. `func (s *StringsValue) Set([]string)`) or capitalize the `value` variable in each *Value struct.

@suyashkumar let me know what you think, and if I'm missing something or if there's another way to create an element with a value :)

**Comment by suyashkumar** [comment]
@IChocked thank you for the good detailed request and suggestion! 

Indeed you are correct that at some point we need to support for creating elements, mostly to support testing downstream (and a `write` package, which hasn't materialized yet in the rewrite). I'd say right now the alpha is mostly ready to test for data parsing, but some of these other use cases still need to be built out.

This is something I've been thinking about recently--I think I'd like to keep all of the Value implementations and their members private (e.g. I recently sent a PR to make the Value implementations private: #103), hopefully there's no reason that you as a Caller need to know about the details of the Value implementation. This keeps the dicom namespace less crowded, and you as a user just need to focus on the public API of the Value (and I'll have more examples on how to work with it). I'm not 100% sure if I like this yet or not, but would love to hear your thoughts as well!

What I will probably do to address your use case is to have an exported function like:

```go
// NewValue creates a new DICOM value for the supplied data. 
// Data must be one of the following types, otherwise and error will be returned.
// Acceptable types: []int, []string, []*Element, PixelDataInfo, ...
func NewValue(data interface{}) (Value, error)
```

And probably an accompanying `func NewElement(tag tag.Tag, vr string, vl int, data interface{}) (*Element, error)`

What do you think?

**Comment by suyashkumar** [comment]
Opened up #108 to add such a NewValue function--does this address your use case? 

Maybe I can also add a MustNewValue function that doesn't return an error (but panics) if the wrong type is sent in, which might be easier to use in tests since it can return a single Value (and probably not a huge deal).

**Comment by suyashkumar** [comment]
Also I should probably set a new tag on the rewrite branch after submitting this, cause a bunch of commits have gone in since `v1.0.0-alpha.2`, though `v1.0.0-alpha.2` should still parse dicoms correctly.

**Comment by wkoszek** [comment]
@suyashkumar A little bit of a background: our CLI uses your library, and since you've showed me a way to write DICOM, I've encompassed it in `segmed` CLI. Brian's request is a result of us not being able to compile the CLI b/c of the missing support for writing. So instead of addressing writing now, I guess what we could do is to use `dcmutil` and run it on a bunch of data and tell you what we get.

**Comment by suyashkumar** [comment]
@wkoszek makes sense, thank you for the context! I will make it a priority to include a working package to write DICOMs in the full 1.0 release -- it's just not there in the alpha version yet (just the DICOM parsing component is complete). Would be great if we could test the parsing component of it while everything else is in progress (feel free to use the dicomutil CLI as you mentioned), and once things are more baked it can be integrated into the segmed CLI :). I am hoping that in about a month everything should be good to go, but we shall see what issues come up, etc.

For the write package, I will probably be able to reuse a lot of the existing write package API wise, and then internally rewrite/replace some of the logic over time as well, if that's the fastest way to unblock users and the release. Will think on it more later this week and start to add in some of that!

**Comment by suyashkumar** [comment]
Closing this out as I think #108 should address this, along with new full-fledged write support! Writes even for sequences are here once #140 is merged :).
