### ISSUE TITLE
Output DICOM Metadata to JSON

### ISSUE THREAD

**Issue by suyashkumar** [suyashkumar/dicom#13]

**Comment by suyashkumar** [comment]
@wkoszek @IChocked not sure if this is useful for y'all but I have a working JSON serialization of the DICOM metadata working (for the rewrite) over in #98. It'll need some cosmetic cleanup, maybe we should skip the PixelData, etc.

I'll also work on a protocol buffer serialization (#38), which will be more type safe, etc.

Considering also serializing to [FHIR imaging study](https://www.hl7.org/fhir/imagingstudy.html) at some point.

**Comment by wkoszek** [comment]
@suyashkumar We may try it out for you (@IChocked is implementing some changes to our CLI to encompass 1.0 API). While JSON support is great to have, I don't envision us becoming active consumers of this API.

**Comment by suyashkumar** [comment]
Great to know, thank you @wkoszek! 

Closing this out, because the changes to support this have been merged in #98
