### ISSUE TITLE
Some files don't have "SamplesPerPixel" header which results in a crash during file parsing

### ISSUE THREAD

**Issue by jasperdenotter** [suyashkumar/dicom#131]
I found a test file which is publicly available here: https://github.com/dragonlet/dicom4android/blob/master/etc/dbf/CT-MONO2-12-lomb-an2

This file does not have a "SamplesPerPixel" header which causes the parser to return an ElementNotFound error when parsing the pixel data. Wondering if it would be a good idea to use a default value of 1 when this header is not present?

**Comment by suyashkumar** [comment]
Thanks for flagging! I saw this too in testing for issue #59. I will look into it a little more, but when working with clinical datasets, I always like to not assume defaults (unless specified in the spec). If something important to reconstructing the image is missing in the raw data, better to flag to the user.

That being said, we can add an override flag the user can supply where we assume defaults like this. However by deafult, I think returning an error to indicate something is not as expected might be safest (unless the spec says to assume a default in this case--I need to double check that).

**Comment by jasperdenotter** [comment]
That makes sense. I agree that it may be safer not to assume any defaults unless they are explicitly documented in the standard. It's probably a good idea to just flag the user that the DICOM they are parsing does not conform to the standard

**Comment by suyashkumar** [comment]
Sounds good, closing this out as WAI then!
