### ISSUE TITLE
Write fails when TransferSyntaxUID header not present

### ISSUE THREAD

**Issue by jasperdenotter** [suyashkumar/dicom#132]
There is a test file here: https://github.com/dragonlet/dicom4android/blob/master/etc/dbf/CR-MONO1-10-chest

This file does not have the "DICM" magic word at the beginning of the dataset so the entire file is parsed with the default transfer syntax of Little Endian Implicit. This means that the resulting dataset returned by the parser does not contain an element for TransferSyntaxUID. When this dataset is re-written the writer returns an ElementNotFound error so i'm wondering if a solution could be to write the Element for the default transfer syntax of Little endian implicit whenever the dataset doesn't contain a transfer syntax.

**Comment by suyashkumar** [comment]
Yeah, we will need to make write changes to support non-standard datasets like this. A couple ways we can go:

1. Write the little endian implicit transfer syntax element as you suggest (but this is technically adding something that didn't exist in the dataset before)
2. Warn that the dataset doesn't have this element, and maybe return an error, unless a certain option is provided (in which case, we write the dataset as is in little endian implicit).

I'm sorta leading towards (2). What do you think?

**Comment by jasperdenotter** [comment]
I agree that 2 may be a better solution since it preserves the exact dataset that the user provided to the write function. I looked quickly at what other toolkits like DCMTK do when faced with non-standard files like this and they fill in the dataset with the default transfer syntax when re-writing. I think approach 2 should suffice though.

**Comment by suyashkumar** [comment]
Closed in #135
