### ISSUE TITLE
EOF error on using Parse function

### ISSUE THREAD

**Issue by lafith** [suyashkumar/dicom#216]
Hi,
I am trying to parse a dicom file recieved as a byte array, send from [Dicomweb-Client](https://dicomweb-client.readthedocs.io/en/latest/introduction.html).  How should I use this function correctly?
![Screenshot from 2021-09-17 23-14-14](https://user-images.githubusercontent.com/39316548/133832216-c7a28ef4-a681-4750-8157-26e01ab9d715.png)

**Comment by suyashkumar** [comment]
Hi there! Can you try this with a DICOM we know works with the library (for example one of the ones in here: https://github.com/suyashkumar/dicom/tree/main/testdata).

Also--I'm not super familiar with DICOM servers, but I think it might be possible that you need to grab some HTTP headers for Content-Length (which could prevent you from having to do io.ReadAll), Content-Type and Content-Encoding (see [here](http://dicom.nema.org/medical/dicom/current/output/html/part18.html#sect_10.5)). From those headers you may need to build metadata elements inserted in front of the actual DICOM payload before parsing (this is my guess looking at a seperate, incompatible [implementation](https://github.com/grailbio/go-netdicom/blob/5b21cc7896c8d66987dfcbb0fc9c14064dfaf499/sampleserver/sampleserver.go#L88-L94)). Like I said, I'm not really familiar with this, but hopefully that points you in somewhat the right direction!

**Comment by lafith** [comment]
I tried with a file from [https://github.com/suyashkumar/dicom/tree/main/testdata](https://github.com/suyashkumar/dicom/tree/main/testdata), still the same error.

**Comment by lafith** [comment]
I have solved the issue. As per this issue-(MGHComputationalPathology/dicomweb-client#54), DicomWeb client was sending data as a [Multipart HTTP  Response](https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html). One can use repos like [mime/multipart](https://pkg.go.dev/mime/multipart#NewReader) to handle such responses.
