### ISSUE TITLE
fatal exit without defer

### ISSUE THREAD

**Issue by maddin200** [suyashkumar/dicom#277]
/cmd\dicomutil\main.go line 67
Code:
	if err != nil {
				log.Fatalf("error parsing data: %v", err) // <-- will not use defer
			}

**Comment by suyashkumar** [comment]
I think you are pointing out that log.Fatalf exits the programs without running the defered functions? Thanks for pointing it out, I'll make some updates in #278 (probably dicomutil in general could use a refactor to be honest).

**Comment by suyashkumar** [comment]
Addressed in dicomutil in #278
