### ISSUE TITLE
Error when parsing with Little Endian Explicit transfer syntax

### ISSUE THREAD

**Issue by patriciaacw** [suyashkumar/dicom#335]
the problem is occurring because the DICOM has an implicit transfer syntax -- unexpected EOF

**Comment by suyashkumar** [comment]
Hi there! Are you using the version of this library at HEAD or the latest tagged version? (If you're using the tagged version, can you try the latest commit of the repo at HEAD?) 

Any additional details could be helpful as well. There are some known edge cases for non-compliant dicoms we still have to address that are discussed here: https://github.com/suyashkumar/dicom/issues/327

**Comment by patriciaacw** [comment]
I was using v1.0.7.

I am new to go, and I am having a bit of trouble trying to get the new version.

After I clone the repo how do I get it to use that version instead?

**Comment by patriciaacw** [comment]
Thank you! That resolved the issue.
