### ISSUE TITLE
Error while running: Operation did not complete successfully because the file contains a virus or potentially unwanted software

### ISSUE THREAD

**Issue by egbertwong** [suyashkumar/dicom#338]
I use this package in go1.20.14 because I need to run the program on Windows 7 and this is the last go version that supports Windows 7.  But now I run the code on Windows 11.

When I add the following code, I can't run the go file. I got the error:

```bash
example/dcmtest: open C:\Users\xxx\AppData\Local\Temp\go-build1652447911\b001\exe\dcmtest.exe: Operation did not complete successfully because the file contains a virus or potentially unwanted software.
```

The code is like:

```golang
dataset, err := dicom.ParseFile(filePath, nil)
```

I used go1.20.14 I got the error. But if I change to go1.22, everything would be okay.

Any suggestions, please?

**Comment by suyashkumar** [comment]
Hey there, I'm not sure sure how to help--this seems like a Windows specific problem and I'm not an expert there. You could maybe try building the program with different build flags :/. Maybe this is a common problem with some Go programs on windows?

**Comment by suyashkumar** [comment]
For now I'm going to close this as wontfix--but if you can add some more thoughts or propose a fix, I'd be all ears! My guess is this has something to do with the compiler itself, so not sure how we can reliably fix this. But open to more info if there is any!
