### ISSUE TITLE
Allow disabling of VR validation during encoding

### ISSUE THREAD

**Issue by kristianvalind** [suyashkumar/dicom#46]
When encoding an element, a VR not matching what is specified in the standard triggers an error. 

For tags where the standard is ambiguous or allows more than one VR type, this is problematic. For example, (0028,0120) Pixel Padding Value somewhat frequently appears as SS, rather than US, which will trigger an error.

One way to solve this would be to allow encoding of elements without VR validation, which also might be useful for situations where writing of non compliant DICOM files might be necessary.

**Comment by suyashkumar** [comment]
Seems like a reasonable feature, even if it's triggered by a parameter. Would you be interested in contributing a patch? If not I can take a look, but most likely will have to happen after Thanksgiving. 

In the meantime, I'm working on an experimental refactor / rewrite (a 1.0) currently on the s/explore branch. and I can include this feature in the roadmap for that release.

**Comment by kristianvalind** [comment]
I have created a pull request (https://github.com/suyashkumar/dicom/pull/47) for my attempt at a patch. It does break API compatibility for the write package, but is supposed to be consistent with the options definition style used in the main package.

**Comment by kristianvalind** [comment]
Closing since we have implemented this functionality in master.
