### ISSUE TITLE
Unknown character set 'ISO_IR 6'. Assuming utf-8 (file offset 360)

### ISSUE THREAD

**Issue by wkoszek** [suyashkumar/dicom#60]
I've hit this issue with 2 many DICOM files coming from 2 different providers/countries.

PyDICOM works fine in this case.

Looks like pydicom considers it as a normal encoding. I think we should too.
```
python_encoding = {

    # default character set for DICOM
    '': default_encoding,

    # alias for latin_1 too (iso_ir_6 exists as an alias to 'ascii')
    'ISO_IR 6': default_encoding,
    'ISO_IR 13': 'shift_jis',
    'ISO_IR 100': 'latin_1',
```

(edit): Same issue with: `Unknown character set 'ISO_IR 192'. Assuming utf-8 (file offset 348)`

**Comment by suyashkumar** [comment]
Thank you for raising this--feel free to submit a PR to add this character set!
