### ISSUE TITLE
ERROR dicom.ReadElement: Undefined length disallowed

### ISSUE THREAD

**Issue by IChocked** [suyashkumar/dicom#82]
This error occurs [here](https://github.com/suyashkumar/dicom/blob/master/parse.go#L351) in parser.go in the ParseNext() function. Something odd that I don't completely understand is that the tags reported in the error, at least for the two example errors below, don't exist in the file (they aren't printed out with [dcmdump](https://support.dcmtk.org/docs/dcmdump.html)). 

**Example errors:**
- ERROR dicom.ReadElement: Undefined length disallowed for VR=\u0000\u0000, tag (0000,0000)[CommandGroupLength] (file offset 61170)
- ERROR dicom.ReadElement: Undefined length disallowed for VR=\u0007\u0000, tag (ffdc,ffc4)[??] (file offset 61006)

**Sample files**
[issue82.zip](https://github.com/suyashkumar/dicom/files/4704720/issue82.zip)

**Comment by suyashkumar** [comment]
I think these are happening due to the same issue in #77. I think this because my quick fix branch seems to parse these files with no issues. (PR #79, branch s/native-pixeldata-fix)

**Comment by suyashkumar** [comment]
feel free to use a build from that branch for evaluating issues. I need to check on some weird behavior I saw with that PR before merging and clean things up, but overall it should unblock you all if you are blocked on it!
